language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python -m unittest discover

after_success:
  - git config --global user.email "tomaszguzialek_flask-api@travis-ci.org"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAG_GENERATION_ACCESS_TOKEN@github.com/tomaszguzialek/flask-api.git --tags
